name: fivekmrun_flutter
description: A mobile application for 5kmRun.bg.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.8.3+393

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  provider: ^5.0.0

  http: ^0.13.0

  collection: ^1.14.11

  shared_preferences: ^2.0.6

  charts_flutter: 
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
      
  intl: ^0.17.0

  strava_flutter: 
      git:
        url: https://github.com/etabakov/strava_flutter.git
        ref: 94ba88c934e021182b4b6abc14287a6cb08dcdea
        
  barcode_flutter: ^1.1.2

  firebase_core: ^1.4.0
  firebase_analytics: ^8.2.0
  # firebase_messaging: ^6.0.13
  firebase_crashlytics: ^2.1.1
  scrollable_positioned_list: ^0.1.9
  url_launcher: ^6.0.7
  transparent_image: ^1.0.0
  rate_my_app: ^1.1.1
  after_layout: ^1.0.7+2
  geocoder: ^0.2.1
  progress_state_button: ^1.0.3  

dependency_overrides:
  plugin_platform_interface: ^2.0.0
  http: ^0.13.0
  url_launcher: ^6.0.7
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  cupertino_icons: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
       - asset: fonts/MyFlutterApp.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

# Generate new app icons command: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo.png"