name: build-ios-app
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: cd fivekmrun_app_flutter && flutter pub get
    - run: cat >./fivekmrun_app_flutter/lib/private/secrets.dart <<'EOL'
            const stravaSecret = "strava-secret";
            const stravaClientId = "strava-client-id";
            const googleMapsKey = "google-maps-key"; 
            EOL
    - run: cd fivekmrun_app_flutter && flutter build ios --release --no-codesign
