name: build-ios-app
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: cd fivekmrun_app_flutter
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
