name: Test Upload
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - shell: bash
        run: touch text.txt
      - shell: bash
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        run: |
          cat << EOF > ./test.txt
          const stravaSecret = '$STRAVA_SECRET';
          const stravaClientId = '$STRAVA_CLIENT_ID';
          const googleMapsKey = '$GOOGLE_MAPS_KEY'; 
          EOF
      - shell: bash
        run: 
          cat ./test.txt
