name: Test Upload
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - shell: bash
        run: touch test.aab
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: bg.fivekmpark.fivekmrun
          releaseFiles: ./test.aab
          releaseName: 3.11.0
          track: production
          status: draft
